CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','member') NOT NULL DEFAULT 'member',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS usage_daily (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  day DATE NOT NULL,
  model VARCHAR(64) NOT NULL,
  tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  requests BIGINT UNSIGNED NOT NULL DEFAULT 0,
  revenue_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  UNIQUE KEY uniq_day_model (day, model)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
